---
driver:
  name: vagrant
  network: 
    - ["forwarded_port", {guest: 3389, host: 33389}] 

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[windows_schannel::default]
    attributes:
